version: '3.9'
services:
  mysql:
    image: mysql:8.1.0
    environment:
      MYSQL_DATABASE: 'naver-land-crawler'
      MYSQL_USER: 'crawler'
      MYSQL_PASSWORD: 'crawler'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    networks:
      - crawler-network
networks:
  crawler-network:
    driver: bridge