import { Test } from '@nestjs/testing';
import { baseNaverLandRequestDto } from '@libs/naver-land-client/tests/test.util';
import { NaverLandCrawler } from '@libs/naver-land-crawler/naver-land.crawler';
import { StartedTestContainer } from 'testcontainers';
import { loadDatabaseContainer } from '@libs/utils/test/load-database-container';
import { TypeOrmModule } from '@nestjs/typeorm';
import { SnakeNamingStrategy } from 'typeorm-naming-strategies';
import { NaverLandCrawlerModule } from '@libs/naver-land-crawler/naver-land-crawler.module';
import { NaverLandCrawlerService } from '@libs/naver-land-crawler/naver-land-crawler.service';
import { NaverLandClientModule } from '@libs/naver-land-client/naver-land-client.module';
import { NaverLandClient } from '@libs/naver-land-client/naver-land.client';

describe('NaverLandCrawler', () => {
    let databaseContainer: StartedTestContainer;

    let naverLandClient: NaverLandClient;
    let naverLandCrawler: NaverLandCrawler;
    let naverLandCrawlerService: NaverLandCrawlerService;

    beforeAll(async () => {
        const dbConfig = {
            databaseName: 'test',
            user: 'test',
            password: 'test',
        };

        databaseContainer = await loadDatabaseContainer(dbConfig).start();

        const moduleRef = await Test.createTestingModule({
            imports: [
                TypeOrmModule.forRoot({
                    type: 'mysql',
                    database: dbConfig.databaseName,
                    username: dbConfig.user,
                    password: dbConfig.password,
                    host: databaseContainer.getHost(),
                    port: databaseContainer.getMappedPort(3306),
                    synchronize: false,
                    autoLoadEntities: true,
                    namingStrategy: new SnakeNamingStrategy(),
                }),
                NaverLandClientModule,
                NaverLandCrawlerModule,
            ],
            providers: [],
            exports: [],
        }).compile();

        naverLandClient = moduleRef.get<NaverLandClient>(NaverLandClient);
        naverLandCrawler = moduleRef.get<NaverLandCrawler>(NaverLandCrawler);
        naverLandCrawlerService = moduleRef.get<NaverLandCrawlerService>(
            NaverLandCrawlerService,
        );
    });

    afterAll(async () => {
        await databaseContainer.stop();
    });

    beforeEach(async () => {
        naverLandClient.getArticleList = jest.fn().mockResolvedValueOnce({
            code: 'mock',
            paidPreSale: {
                preSaleComplexNumber: 6026967,
                preSaleComplexName: '서초아트래디앙',
                preSaleAddress: '서울시 서초구 서초동',
                preSaleStageCode: 'C12',
                preSaleTypeCode: 'IA01',
                preSaleFormCode: '11',
                occupancyYearMonth: '2023.06',
                thumbnail:
                    'https://landthumb-phinf.pstatic.net/20230331_18/land_naver_1680242161860t1AcD_PNG/uploadfile_202303233002535.png',
                featureMarkTypeCode: '1',
                minPreSalePrice: 1690000000,
                maxPreSalePrice: 2700000000,
                minPreSaleArea: 60.74,
                maxPreSaleArea: 102.17,
                totalHouseholdsNumber: 24,
                preSaleHouseholdsNumber: 24,
                xcoordinate: 127.010792,
                ycoordinate: 37.486794,
                preSaleDetailsPageURL:
                    'https://isale.land.naver.com/NewiSaleMobile/Home/#SYDetail?build_dtl_cd=6026967&supp_cd=9038457',
            },
            hasPaidPreSale: true,
            more: true,
            TIME: false,
            z: 13,
            page: 1,
            body: [
                {
                    atclNo: '2346244290',
                    cortarNo: '1117013100',
                    atclNm: '나인원한남',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B1',
                    tradTpNm: '전세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '1/9',
                    prc: 1300000,
                    rentPrc: 0,
                    hanPrc: '130억',
                    spc1: '334',
                    spc2: '273.94',
                    direction: '남향',
                    atclCfmYmd: '23.10.27.',
                    repImgUrl:
                        '/20231027_109/land_naver_169837389426290dv6_JPEG/1698370876251275.jpg',
                    repImgTpCd: '10',
                    repImgThumb: 'f130_98',
                    lat: 37.535646,
                    lng: 127.002416,
                    atclFetrDesc: '실사용131P 복층 넓은마당과 테라스 차고까지',
                    tagList: ['4년이내', '융자금없는', '테라스'],
                    bildNm: '103동',
                    minute: 0,
                    sameAddrCnt: 2,
                    sameAddrDirectCnt: 0,
                    sameAddrHash:
                        '23A01B1N64f2d56a93e5a497fd8d10fa57311e8519b010d3182ece8bbeff6ab396626d42',
                    sameAddrMaxPrc: '130억',
                    sameAddrMinPrc: '130억',
                    cpid: 'NEONET',
                    cpNm: '부동산뱅크',
                    cpCnt: 2,
                    rltrNm: '네스트공인중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'NEONET',
                        mobileArticleLinkTypeCode: 'NONE',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: false,
                        mobileArticleLinkUseAtCpName: false,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 810,
                },
                {
                    atclNo: '2344023574',
                    cortarNo: '1120011400',
                    atclNm: '갤러리아포레(주상복합)',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B2',
                    tradTpNm: '월세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '중/45',
                    prc: 450000,
                    rentPrc: 500,
                    hanPrc: '45억',
                    spc1: '329',
                    spc2: '241.93',
                    direction: '남향',
                    atclCfmYmd: '23.10.14.',
                    lat: 37.545781,
                    lng: 127.042343,
                    atclFetrDesc:
                        '갤러리아포레, 100. 탁트인 서울숲뷰. 한강뷰. 내부인테리어깨끗',
                    tagList: ['15년이내', '융자금없는', '역세권', '대형평수'],
                    bildNm: '102동',
                    minute: 0,
                    sameAddrCnt: 1,
                    sameAddrDirectCnt: 0,
                    cpid: 'SERVE',
                    cpNm: '부동산써브',
                    cpCnt: 1,
                    rltrNm: '타워공인중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'SERVE',
                        mobileArticleUrl:
                            'https://m.serve.co.kr/naver/rd.asp?UID=',
                        mobileArticleLinkTypeCode: 'CPNAMEONLY',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: false,
                        mobileArticleLinkUseAtCpName: true,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 420,
                },
                {
                    atclNo: '2345088301',
                    cortarNo: '1165010700',
                    atclNm: '래미안원베일리',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B1',
                    tradTpNm: '전세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '35/35',
                    prc: 850000,
                    rentPrc: 0,
                    hanPrc: '85억',
                    spc1: '315',
                    spc2: '234.82',
                    direction: '남서향',
                    atclCfmYmd: '23.10.20.',
                    lat: 37.506748,
                    lng: 126.997619,
                    atclFetrDesc: '귀한 펜트',
                    tagList: ['2년이내', '융자금없는', '대단지', '대형평수'],
                    bildNm: '106동',
                    minute: 0,
                    sameAddrCnt: 2,
                    sameAddrDirectCnt: 0,
                    sameAddrHash:
                        '24A01B1Nbc9f61e622b29422e27457c5a8fddb9db22f987ff891e09d8d3d5748f3baa5b9',
                    sameAddrMaxPrc: '90억',
                    sameAddrMinPrc: '85억',
                    cpid: 'ten',
                    cpNm: '텐컴즈',
                    cpCnt: 1,
                    rltrNm: '1000억1등부동산중개법인주식회사',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'ten',
                        mobileArticleLinkTypeCode: 'NONE',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: false,
                        mobileArticleLinkUseAtCpName: false,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 670,
                },
                {
                    atclNo: '2345053293',
                    cortarNo: '1165010700',
                    atclNm: '래미안원베일리',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B1',
                    tradTpNm: '전세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '고/35',
                    prc: 890000,
                    rentPrc: 0,
                    hanPrc: '89억',
                    spc1: '315',
                    spc2: '234.82',
                    direction: '남향',
                    atclCfmYmd: '23.10.20.',
                    lat: 37.508098,
                    lng: 126.998644,
                    atclFetrDesc: '귀한 펜트',
                    tagList: ['2년이내', '융자금없는', '대단지', '대형평수'],
                    bildNm: '120동',
                    minute: 0,
                    sameAddrCnt: 1,
                    sameAddrDirectCnt: 0,
                    cpid: 'ten',
                    cpNm: '텐컴즈',
                    cpCnt: 1,
                    rltrNm: '1000억1등부동산중개법인주식회사',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'ten',
                        mobileArticleLinkTypeCode: 'NONE',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: false,
                        mobileArticleLinkUseAtCpName: false,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 540,
                },
                {
                    atclNo: '2344627122',
                    cortarNo: '1165010700',
                    atclNm: '래미안원베일리',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B1',
                    tradTpNm: '전세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '고/35',
                    prc: 850000,
                    rentPrc: 0,
                    hanPrc: '85억',
                    spc1: '315',
                    spc2: '234.82',
                    direction: '북서향',
                    atclCfmYmd: '23.10.18.',
                    repImgUrl:
                        '/20231018_222/land_naver_1697592164285Wlw1x_JPEG/15130332_20231017200711.jpg',
                    repImgTpCd: '10',
                    repImgThumb: 'f130_98',
                    lat: 37.505899,
                    lng: 126.998206,
                    atclFetrDesc:
                        'V95펜트. 파노라마한강뷰. 고층남산뷰. 명품커뮤니티. 조정가',
                    tagList: ['2년이내', '융자금없는', '역세권'],
                    bildNm: '109동',
                    minute: 0,
                    sameAddrCnt: 1,
                    sameAddrDirectCnt: 0,
                    cpid: 'SERVE',
                    cpNm: '부동산써브',
                    cpCnt: 1,
                    rltrNm: '스카이공인중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'SERVE',
                        mobileArticleUrl:
                            'https://m.serve.co.kr/naver/rd.asp?UID=',
                        mobileArticleLinkTypeCode: 'CPNAMEONLY',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: false,
                        mobileArticleLinkUseAtCpName: true,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 520,
                },
                {
                    atclNo: '2345321175',
                    cortarNo: '1165010700',
                    atclNm: '래미안원베일리',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B1',
                    tradTpNm: '전세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '35/35',
                    prc: 980000,
                    rentPrc: 0,
                    hanPrc: '98억',
                    spc1: '315',
                    spc2: '234.82',
                    direction: '북향',
                    atclCfmYmd: '23.10.21.',
                    repImgUrl:
                        '/20231021_297/land_naver_1697868427802SPwWB_JPEG/1689747325850009.jpg',
                    repImgTpCd: '10',
                    repImgThumb: 'f130_98',
                    lat: 37.507595,
                    lng: 126.997448,
                    atclFetrDesc:
                        '95원베일리 파노라마 한강뷰 펜트하우스의 주인공이 될 분을 모십니다',
                    tagList: ['2년이내', '융자금없는', '대단지'],
                    bildNm: '104동',
                    minute: 0,
                    sameAddrCnt: 1,
                    sameAddrDirectCnt: 0,
                    cpid: 'NEONET',
                    cpNm: '부동산뱅크',
                    cpCnt: 1,
                    rltrNm: '단지내타임공인중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'NEONET',
                        mobileArticleLinkTypeCode: 'NONE',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: false,
                        mobileArticleLinkUseAtCpName: false,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 710,
                },
                {
                    atclNo: '2346157953',
                    cortarNo: '1165010700',
                    atclNm: '래미안원베일리',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B1',
                    tradTpNm: '전세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '고/35',
                    prc: 800000,
                    rentPrc: 0,
                    hanPrc: '80억',
                    spc1: '315',
                    spc2: '234.82',
                    direction: '북향',
                    atclCfmYmd: '23.10.26.',
                    lat: 37.507595,
                    lng: 126.997448,
                    atclFetrDesc: '팬트,한강뷰',
                    tagList: ['2년이내', '융자금없는', '대단지', '대형평수'],
                    bildNm: '104동',
                    minute: 0,
                    sameAddrCnt: 1,
                    sameAddrDirectCnt: 0,
                    cpid: 'ten',
                    cpNm: '텐컴즈',
                    cpCnt: 1,
                    rltrNm: '오렌지공인중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'ten',
                        mobileArticleLinkTypeCode: 'NONE',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: false,
                        mobileArticleLinkUseAtCpName: false,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 660,
                },
                {
                    atclNo: '2346360438',
                    cortarNo: '1120011500',
                    atclNm: '서울숲힐스테이트',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B2',
                    tradTpNm: '월세',
                    vrfcTpCd: 'OWNER',
                    flrInfo: '고/29',
                    prc: 100000,
                    rentPrc: 1200,
                    hanPrc: '10억',
                    spc1: '304',
                    spc2: '239.7',
                    direction: '남향',
                    atclCfmYmd: '23.10.27.',
                    lat: 37.541307,
                    lng: 127.051792,
                    atclFetrDesc:
                        '92 복층펜트  탁트인 한강조망  테라스  전체확장  빠른입주가',
                    tagList: ['15년이내', '테라스', '복층', '대형평수'],
                    bildNm: '102동',
                    minute: 0,
                    sameAddrCnt: 1,
                    sameAddrDirectCnt: 0,
                    cpid: 'R114',
                    cpNm: '부동산114',
                    cpCnt: 1,
                    rltrNm: '힐스테이트한강공인',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'R114',
                        mobileArticleUrl:
                            'https://m.r114.com/?_c=redirect&_m=ArticleFromNbp&UID=',
                        mobileArticleLinkTypeCode: 'ALL',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: true,
                        mobileArticleLinkUseAtCpName: true,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 910,
                },
                {
                    atclNo: '2343334717',
                    cortarNo: '1165010700',
                    atclNm: '반포자이',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B1',
                    tradTpNm: '전세',
                    vrfcTpCd: 'NDOC1',
                    flrInfo: '고/27',
                    prc: 400000,
                    rentPrc: 0,
                    hanPrc: '40억',
                    spc1: '301',
                    spc2: '244.97',
                    direction: '남동향',
                    atclCfmYmd: '23.10.10.',
                    repImgUrl:
                        '/20231010_18/land_naver_1696937957132p0gEL_JPEG/2023101015560861732_44133_ws.jpg',
                    repImgTpCd: '10',
                    repImgThumb: 'f130_98',
                    lat: 37.505438,
                    lng: 127.015634,
                    atclFetrDesc: '91  주인직접   확장특올수리   입주일조율',
                    tagList: ['15년이내', '융자금없는', '올수리'],
                    bildNm: '129동',
                    minute: 0,
                    sameAddrCnt: 1,
                    sameAddrDirectCnt: 0,
                    cpid: 'asil',
                    cpNm: '아실',
                    cpCnt: 1,
                    rltrNm: '부일공인중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'asil',
                        mobileArticleUrl:
                            'https://asil.kr/app/sale_info.jsp?UID=',
                        mobileArticleLinkTypeCode: 'ALL',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: true,
                        mobileArticleLinkUseAtCpName: true,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 550,
                },
                {
                    atclNo: '2345643087',
                    cortarNo: '1165010700',
                    atclNm: '반포자이',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B2',
                    tradTpNm: '월세',
                    vrfcTpCd: 'DOCV2',
                    flrInfo: '고/28',
                    prc: 30000,
                    rentPrc: 1400,
                    hanPrc: '3억',
                    spc1: '301',
                    spc2: '244.62',
                    direction: '남향',
                    atclCfmYmd: '23.10.24.',
                    lat: 37.507087,
                    lng: 127.012401,
                    atclFetrDesc:
                        '91 월세 반전세 특인테리어 로얄층 풀옵션 전망예쁜남향집 입주협의가능',
                    tagList: ['15년이내', '융자금없는', '역세권', '대단지'],
                    bildNm: '111동',
                    minute: 0,
                    sameAddrCnt: 4,
                    sameAddrDirectCnt: 0,
                    sameAddrHash:
                        '24A01B2N6f86cb09fa48a2d603ad7205286d0ca5818d11670032e0b9eb436618796d1315',
                    sameAddrMaxPrc: '3억',
                    sameAddrMaxPrc2: '1,500',
                    sameAddrMinPrc: '3억',
                    sameAddrMinPrc2: '1,400',
                    cpid: 'asil',
                    cpNm: '아실',
                    cpCnt: 2,
                    rltrNm: '반포자이홈런공인중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'asil',
                        mobileArticleUrl:
                            'https://asil.kr/app/sale_info.jsp?UID=',
                        mobileArticleLinkTypeCode: 'ALL',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: true,
                        mobileArticleLinkUseAtCpName: true,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 740,
                },
                {
                    atclNo: '2343535923',
                    cortarNo: '1165010700',
                    atclNm: '반포자이',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B1',
                    tradTpNm: '전세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '고/28',
                    prc: 400000,
                    rentPrc: 0,
                    hanPrc: '40억',
                    spc1: '301',
                    spc2: '244.62',
                    direction: '남향',
                    atclCfmYmd: '23.10.11.',
                    repImgUrl:
                        '/20231011_26/land_naver_1697008616797UMIAY_JPEG/2023101116073482314_44390_ws.jpg',
                    repImgTpCd: '10',
                    repImgThumb: 'f130_98',
                    lat: 37.507087,
                    lng: 127.012401,
                    atclFetrDesc:
                        '9  1  완벽한 신규 입주  최근 올수리  즉시 입주   정남 풀옵션',
                    tagList: ['15년이내', '융자금없는', '올수리'],
                    bildNm: '111동',
                    minute: 0,
                    sameAddrCnt: 1,
                    sameAddrDirectCnt: 0,
                    cpid: 'asil',
                    cpNm: '아실',
                    cpCnt: 1,
                    rltrNm: '반포중앙공인중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'asil',
                        mobileArticleUrl:
                            'https://asil.kr/app/sale_info.jsp?UID=',
                        mobileArticleLinkTypeCode: 'ALL',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: true,
                        mobileArticleLinkUseAtCpName: true,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 380,
                },
                {
                    atclNo: '2346198213',
                    cortarNo: '1165010800',
                    atclNm: '아크로비스타(주상복합)',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B1',
                    tradTpNm: '전세',
                    vrfcTpCd: 'NDOC1',
                    flrInfo: '고/37',
                    prc: 430000,
                    rentPrc: 0,
                    hanPrc: '43억',
                    spc1: '300',
                    spc2: '238.62',
                    direction: '남향',
                    atclCfmYmd: '23.10.27.',
                    lat: 37.498364,
                    lng: 127.013375,
                    atclFetrDesc:
                        '92.남향.최고급인테리어 펜트하우스.파노라마전망,',
                    tagList: ['25년이내', '융자금없는', '대형평수', '방세개'],
                    bildNm: 'B동',
                    minute: 0,
                    sameAddrCnt: 8,
                    sameAddrDirectCnt: 0,
                    sameAddrHash:
                        '22A01B1N519c71376965f362a200820d052492c96b0362c7084e50ee3d01c16d03f6a90e',
                    sameAddrMaxPrc: '43억',
                    sameAddrMinPrc: '43억',
                    cpid: 'asil',
                    cpNm: '아실',
                    cpCnt: 6,
                    rltrNm: '엘루크우리공인중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'asil',
                        mobileArticleUrl:
                            'https://asil.kr/app/sale_info.jsp?UID=',
                        mobileArticleLinkTypeCode: 'ALL',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: true,
                        mobileArticleLinkUseAtCpName: true,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 910,
                },
                {
                    atclNo: '2346501760',
                    cortarNo: '1165010800',
                    atclNm: '아크로비스타(주상복합)',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B2',
                    tradTpNm: '월세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '고/37',
                    prc: 250000,
                    rentPrc: 800,
                    hanPrc: '25억',
                    spc1: '300',
                    spc2: '238.62',
                    direction: '남향',
                    atclCfmYmd: '23.10.28.',
                    lat: 37.498364,
                    lng: 127.013375,
                    tagList: ['25년이내', '융자금없는', '대형평수', '방세개'],
                    bildNm: 'B동',
                    minute: 0,
                    sameAddrCnt: 2,
                    sameAddrDirectCnt: 0,
                    sameAddrHash:
                        '22A01B2N01380b3a1e889329d86b6e3196c8e2cd89192095ae4c8cd6a684a7fb1c4a1bda',
                    sameAddrMaxPrc: '25억',
                    sameAddrMaxPrc2: '800',
                    sameAddrMinPrc: '7억 5,000',
                    sameAddrMinPrc2: '1,500',
                    cpid: 'SERVE',
                    cpNm: '부동산써브',
                    cpCnt: 2,
                    rltrNm: '럭셔리앤하우스부동산중개(주) 여의도점',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'SERVE',
                        mobileArticleUrl:
                            'https://m.serve.co.kr/naver/rd.asp?UID=',
                        mobileArticleLinkTypeCode: 'CPNAMEONLY',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: false,
                        mobileArticleLinkUseAtCpName: true,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 700,
                },
                {
                    atclNo: '2346500522',
                    cortarNo: '1165010800',
                    atclNm: '아크로비스타(주상복합)',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B1',
                    tradTpNm: '전세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '고/37',
                    prc: 430000,
                    rentPrc: 0,
                    hanPrc: '43억',
                    spc1: '300',
                    spc2: '238.62',
                    direction: '남향',
                    atclCfmYmd: '23.10.28.',
                    lat: 37.498364,
                    lng: 127.013375,
                    tagList: ['25년이내', '융자금없는', '대형평수', '방세개'],
                    bildNm: 'B동',
                    minute: 0,
                    sameAddrCnt: 2,
                    sameAddrDirectCnt: 0,
                    sameAddrHash:
                        '22A01B1N01380b3a1e889329d86b6e3196c8e2cd89192095ae4c8cd6a684a7fb1c4a1bda',
                    sameAddrMaxPrc: '43억',
                    sameAddrMinPrc: '43억',
                    cpid: 'SERVE',
                    cpNm: '부동산써브',
                    cpCnt: 2,
                    rltrNm: '럭셔리앤하우스부동산중개(주) 여의도점',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'SERVE',
                        mobileArticleUrl:
                            'https://m.serve.co.kr/naver/rd.asp?UID=',
                        mobileArticleLinkTypeCode: 'CPNAMEONLY',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: false,
                        mobileArticleLinkUseAtCpName: true,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 700,
                },
                {
                    atclNo: '2343788220',
                    cortarNo: '1165010800',
                    atclNm: '아크로비스타(주상복합)',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B2',
                    tradTpNm: '월세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '고/37',
                    prc: 130000,
                    rentPrc: 1200,
                    hanPrc: '13억',
                    spc1: '300',
                    spc2: '238.62',
                    direction: '남향',
                    atclCfmYmd: '23.10.12.',
                    repImgUrl:
                        '/20231012_212/land_naver_1697099525216HV5q4_JPEG/14478797_2023971138611.jpg',
                    repImgTpCd: '10',
                    repImgThumb: 'f130_98',
                    lat: 37.498364,
                    lng: 127.013375,
                    atclFetrDesc:
                        '아크로비스타 92. 고층 특급인테리어. 1년전수리. 주인거주중. 입주협의',
                    tagList: ['25년이내', '융자금없는', '대형평수'],
                    bildNm: 'B동',
                    minute: 0,
                    sameAddrCnt: 1,
                    sameAddrDirectCnt: 0,
                    cpid: 'SERVE',
                    cpNm: '부동산써브',
                    cpCnt: 1,
                    rltrNm: '코지하우스공인중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'SERVE',
                        mobileArticleUrl:
                            'https://m.serve.co.kr/naver/rd.asp?UID=',
                        mobileArticleLinkTypeCode: 'CPNAMEONLY',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: false,
                        mobileArticleLinkUseAtCpName: true,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 380,
                },
                {
                    atclNo: '2343651562',
                    cortarNo: '1165010700',
                    atclNm: '반포자이',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B2',
                    tradTpNm: '월세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '중/27',
                    prc: 30000,
                    rentPrc: 1500,
                    hanPrc: '3억',
                    spc1: '297',
                    spc2: '244.54',
                    direction: '남향',
                    atclCfmYmd: '23.10.12.',
                    repImgUrl:
                        '/20231012_249/land_naver_16970814342777ddnt_JPEG/2023101211030660444_44390_ws.jpg',
                    repImgTpCd: '10',
                    repImgThumb: 'f130_98',
                    lat: 37.507796,
                    lng: 127.012131,
                    atclFetrDesc:
                        '9  0  완벽한 신규 입주  최근 올수리  즉시 입주   정남 풀옵션',
                    tagList: ['15년이내', '융자금없는', '올수리'],
                    bildNm: '113동',
                    minute: 0,
                    sameAddrCnt: 1,
                    sameAddrDirectCnt: 0,
                    cpid: 'asil',
                    cpNm: '아실',
                    cpCnt: 1,
                    rltrNm: '반포중앙공인중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'asil',
                        mobileArticleUrl:
                            'https://asil.kr/app/sale_info.jsp?UID=',
                        mobileArticleLinkTypeCode: 'ALL',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: true,
                        mobileArticleLinkUseAtCpName: true,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 400,
                },
                {
                    atclNo: '2346458497',
                    cortarNo: '1156011000',
                    atclNm: '대우트럼프월드Ⅰ(주상복합)',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B1',
                    tradTpNm: '전세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '39/40',
                    prc: 240000,
                    rentPrc: 0,
                    hanPrc: '24억',
                    spc1: '296',
                    spc2: '244.91',
                    direction: '북동향',
                    atclCfmYmd: '23.10.28.',
                    lat: 37.517538,
                    lng: 126.932569,
                    atclFetrDesc:
                        '92전세 o확실한진행 o펜트하우스 o고품격주거공간 o360파노라마여의도뷰',
                    tagList: ['25년이내', '융자금없는', '역세권', '대형평수'],
                    bildNm: 'B동',
                    minute: 0,
                    sameAddrCnt: 2,
                    sameAddrDirectCnt: 0,
                    sameAddrHash:
                        '28A01B1Nccfdf583061526633994fb1c27bbe2f16cddf38cc3ffefd4f9305b08e9b9f217',
                    sameAddrMaxPrc: '24억',
                    sameAddrMinPrc: '24억',
                    cpid: 'hkdotcom',
                    cpNm: '한경부동산',
                    cpCnt: 1,
                    rltrNm: '여의도GS자이공인중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'hkdotcom',
                        mobileArticleLinkTypeCode: 'NONE',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: false,
                        mobileArticleLinkUseAtCpName: false,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 850,
                },
                {
                    atclNo: '2346250229',
                    cortarNo: '1156011000',
                    atclNm: '대우트럼프월드Ⅰ(주상복합)',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B1',
                    tradTpNm: '전세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '39/40',
                    prc: 240000,
                    rentPrc: 0,
                    hanPrc: '24억',
                    spc1: '296',
                    spc2: '244.91',
                    direction: '남향',
                    atclCfmYmd: '23.10.27.',
                    lat: 37.517538,
                    lng: 126.932569,
                    tagList: ['25년이내', '융자금없는', '역세권', '대형평수'],
                    bildNm: 'B동',
                    minute: 0,
                    sameAddrCnt: 2,
                    sameAddrDirectCnt: 0,
                    sameAddrHash:
                        '28A01B1Nf91cffbcfc7745c44ff45b492fce1abc79011995c6193e5bee0fcb40aa76fbc3',
                    sameAddrMaxPrc: '24억',
                    sameAddrMinPrc: '24억',
                    cpid: 'sunbang',
                    cpNm: '선방',
                    cpCnt: 2,
                    rltrNm: '여의도자이중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'sunbang',
                        mobileArticleLinkTypeCode: 'NONE',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: false,
                        mobileArticleLinkUseAtCpName: false,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 830,
                },
                {
                    atclNo: '2346233609',
                    cortarNo: '1156011000',
                    atclNm: '대우트럼프월드Ⅰ(주상복합)',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B1',
                    tradTpNm: '전세',
                    vrfcTpCd: 'DOC',
                    flrInfo: '38/40',
                    prc: 260000,
                    rentPrc: 0,
                    hanPrc: '26억',
                    spc1: '296',
                    spc2: '244.91',
                    direction: '남향',
                    atclCfmYmd: '23.10.27.',
                    lat: 37.517538,
                    lng: 126.932569,
                    atclFetrDesc:
                        '펜트92 한강조망 샛강공원 파노라마 전용주차 전용테라스 여의도최고물건',
                    tagList: ['25년이내', '융자금없는', '테라스', '역세권'],
                    bildNm: 'B동',
                    minute: 0,
                    sameAddrCnt: 3,
                    sameAddrDirectCnt: 0,
                    sameAddrHash:
                        '28A01B1Na290b8d67de81037ae80e0986bf236eabbb0cba6727a43eb70225b9fc614795b',
                    sameAddrMaxPrc: '26억',
                    sameAddrMinPrc: '26억',
                    cpid: 'sunbang',
                    cpNm: '선방',
                    cpCnt: 3,
                    rltrNm: '여의도자이중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'sunbang',
                        mobileArticleLinkTypeCode: 'NONE',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: false,
                        mobileArticleLinkUseAtCpName: false,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 830,
                },
                {
                    atclNo: '2345741362',
                    cortarNo: '1171010200',
                    atclNm: '잠실더샵스타파크(주상복합)',
                    atclStatCd: 'R0',
                    rletTpCd: 'A01',
                    uprRletTpCd: 'A01',
                    rletTpNm: '아파트',
                    tradTpCd: 'B1',
                    tradTpNm: '전세',
                    vrfcTpCd: 'TEL',
                    flrInfo: '중/39',
                    prc: 270000,
                    rentPrc: 0,
                    hanPrc: '27억',
                    spc1: '294',
                    spc2: '240.48',
                    direction: '남동향',
                    atclCfmYmd: '23.10.24.',
                    lat: 37.51667,
                    lng: 127.102171,
                    atclFetrDesc: '방4,더블역세권',
                    tagList: [
                        '25년이내',
                        '융자금없는',
                        '대형평수',
                        '방네개이상',
                    ],
                    bildNm: '102동',
                    minute: 0,
                    sameAddrCnt: 5,
                    sameAddrDirectCnt: 0,
                    sameAddrHash:
                        '23A01B1Nac9d1556312e65c607c1f60fb662ef4582bdfaac0070ee00b2eba332eadfbc68',
                    sameAddrMaxPrc: '27억',
                    sameAddrMinPrc: '27억',
                    cpid: 'R114',
                    cpNm: '부동산114',
                    cpCnt: 4,
                    rltrNm: 'JS공인중개사사무소',
                    directTradYn: 'N',
                    minMviFee: 0,
                    maxMviFee: 0,
                    etRoomCnt: 0,
                    tradePriceHan: '',
                    tradeRentPrice: 0,
                    tradeCheckedByOwner: false,
                    cpLinkVO: {
                        cpId: 'R114',
                        mobileArticleUrl:
                            'https://m.r114.com/?_c=redirect&_m=ArticleFromNbp&UID=',
                        mobileArticleLinkTypeCode: 'ALL',
                        mobileBmsInspectPassYn: 'Y',
                        pcArticleLinkUseAtArticleTitle: false,
                        pcArticleLinkUseAtCpName: false,
                        mobileArticleLinkUseAtArticleTitle: true,
                        mobileArticleLinkUseAtCpName: true,
                    },
                    dtlAddrYn: 'N',
                    dtlAddr: '',
                    point: 690,
                },
            ],
        });
    });

    it('naverLandArticle Save 테스트', async () => {
        const articles = await naverLandCrawler.run(
            baseNaverLandRequestDto({
                z: 13,
                lat: 37.5030847,
                lon: 126.996848,
                btm: 37.4390515,
                lft: 126.832053,
                top: 37.567063,
                rgt: 127.1616429,
                page: 1,
                maxPage: 1,
            }),
        );

        const savedNaverLandArticles = await naverLandCrawlerService.findAll();
        expect(savedNaverLandArticles.length).toBe(20);

        for (const savedNaverLandArticle of savedNaverLandArticles) {
            expect(savedNaverLandArticle.region1).toBeDefined();
            expect(savedNaverLandArticle.region2).toBeDefined();
            expect(savedNaverLandArticle.region3).toBeDefined();
        }
    });
});
