name: kubernetes-deploy

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Manual Deploy'
        # Default value if no value is explicitly provided
        default: 'ManualDeploy'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGESTOKEN }}
    - name: Build and push (Crawler)
      uses: docker/build-push-action@v3
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/crawler/crawler-node:latest