name: kubernetes-deploy

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Deployment Reason'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repository Checkout
      - uses: actions/checkout@v3

      # Docker Hub login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGESTOKEN }}

        # Build and push (Crawler)
      - name: Build and push (Crawler)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/crawler/crawler-node:latest